import { WorksData } from "./types";

const worksData: WorksData = {
  id: [
    {
      category: 0,
      clientLogo: "/images/clients/gerindra.png",
      clientName: "Myself",
      title: "Hanya Personal Website Lama Saya yang Pertama",
      image: "/images/works/0.png",
      imageAlter: "/images/works/0.png",
      solution:
        "Membuat tampilan dengan gaya minimalis dengan React dan ChakraUI. Data konten dari personal website tersebut statis dan terdapat 2 versi bahasa (indonesia dan inggris)",
      narrative:
        "Sebagai seorang fresh graduate saya sebagai web developer ingin memiliki personal website. Saat itu pengetahuan React saya masih pemula namun memiliki sense of design yang sudah bagus karena pengalaman saya sebagai desainer grafis dalam 1 tahun. Jadi saya membuat personal website saya dengan kemampuan yang saya miliki saat itu.",
      ss: [
        "/images/works/0/ss/0.png",
        "/images/works/0/ss/1.png",
        "/images/works/0/ss/2.png",
        "/images/works/0/ss/3.png",
        "/images/works/0/ss/4.png",
        "/images/works/0/ss/5.png",
        "/images/works/0/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://fatwalinoveraold.netlify.app/",
    },
    {
      category: 0,
      clientLogo: "/images/clients/gerindra.png",
      clientName: "Myself",
      title: "Just My Second Old Personal Website",
      image: "/images/works/-1.png",
      imageAlter: "/images/works/-1.png",
      solution:
        "Membuat desain dengan gaya exploded menggunakan React dan ChakraUI. Data konten website pribadi ini bersifat statis dan terdapat 2 versi bahasa (Indonesia dan Inggris).",
      narrative:
        "Sebagai seorang freshgraduate, saya ingin mempunyai website pribadi. Pada saat itu, pengetahuan saya tentang React masih dasar tetapi saya memiliki pemahaman yang baik tentang desain karena pengalaman saya selama 1 tahun sebagai desainer grafis. Jadi, saya membuat website pribadi dengan keterampilan yang saya miliki saat itu.",
      ss: [
        "/images/works/-1/ss/0.png",
        "/images/works/-1/ss/1.png",
        "/images/works/-1/ss/2.png",
        "/images/works/-1/ss/3.png",
        "/images/works/-1/ss/4.png",
        "/images/works/-1/ss/5.png",
        "/images/works/-1/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://fatwalinoveraold2.netlify.app/",
    },

    {
      category: 0,
      clientLogo: "/images/clients/poltekkes.png",
      clientName: "POLTEKKES SEMARANG",
      title:
        "Platform untuk Transaksi Pengujian Laboratorium dan Dasboard Admin untuk Mengelola Sistem",
      image: "/images/works/1.png",
      imageAlter: "/images/works/1_alter.png",
      solution:
        "Saya sebagai frontend developer mengerjakan tampilan sesuai dengan desain yang sudah dibuat oleh rekan tim dan juga implementasi request API",
      narrative:
        "Poltekkes meminta sebuah sistem untuk pengujian lab. Jadi aa 2 pengguna yaitu customer dan admin. Customer dapat membuat akun dan mengajukan pengujian laboratorium dan memantau prosesnya. Admin dapat mengelola sistem tersebut seperti metode pengujian, biaya, dashboard dll.",
      ss: [
        "/images/works/1/ss/0.png",
        "/images/works/1/ss/1.png",
        "/images/works/1/ss/2.png",
        "/images/works/1/ss/3.png",
        "/images/works/1/ss/4.png",
        "/images/works/1/ss/5.png",
        "/images/works/1/ss/6.png",
        "/images/works/1/ss/7.png",
        "/images/works/1/ss/8.png",
        "/images/works/1/ss/9.png",
        "/images/works/1/ss/10.png",
        "/images/works/1/ss/11.png",
        "/images/works/1/ss/12.png",
        "/images/works/1/ss/13.png",
        "/images/works/1/ss/14.png",
        "/images/works/1/ss/15.png",
        "/images/works/1/ss/16.png",
        "/images/works/1/ss/17.png",
      ],
      ssScrollLength: 450,
      link: "https://lab.distrostudio.org/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title:
        "Webapp Admin untuk Mengelola Situs Web Landing Page, Blog, Online Course",
      image: "/images/works/2.png",
      imageAlter: "/images/works/2_alter.png",
      solution:
        "Membuat backend menggunakan laravel, yang pertama dibuat adalah sistem role dulu (create akun admin). Kemudian membuat logic CRUD blog dan course.",
      narrative:
        "Dibutuhkan webapp admin untuk mengelola website-website yang akan dibuat nanti. Aksi seperti membuat, memperbarui, menghapus, restore harus ada dan webapp admin ini juga memiliki role admin tertentu seperti admin online course, admin blog, dll.",
      ss: [
        "/images/works/5/ss/0.png",
        "/images/works/5/ss/1.png",
        "/images/works/5/ss/2.png",
        "/images/works/5/ss/3.png",
        "/images/works/5/ss/4.png",
        "/images/works/5/ss/5.png",
        "/images/works/5/ss/6.png",
        "/images/works/5/ss/7.png",
        "/images/works/5/ss/8.png",
      ],
      ssScrollLength: 450,
      // link: "https://admin2.kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title:
        "Landing Page Kubu.id yang Berisi Semua Web Kubu.id (Kubu Mobile App, Blog, Online Course)",
      image: "/images/works/3.png",
      imageAlter: "/images/works/3_alter.png",
      solution:
        "Membuat backend CMS (Content Management System) menggunakan laravel dan membuat frontend end user menggunakan React dan ChakraUI (+dark mode)",
      narrative:
        "Kubu.id adalah aplikasi dengan basis komunitas online untuk kamu yang sudah bekerja dan bagi calon pekerja. Tujuannya menjadi pusat pengetahuan dan informasi terkait ketenagakerjaan, sebagai media untuk konsultasi online dengan profesional, mengembangkan jaringan dan saling berbagi informasi.",
      ss: [
        "/images/works/4/ss/0.png",
        "/images/works/4/ss/1.png",
        "/images/works/4/ss/2.png",
        "/images/works/4/ss/3.png",
        "/images/works/4/ss/4.png",
        "/images/works/4/ss/5.png",
      ],
      ssScrollLength: 450,
      link: "https://kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title: "Blog Kubu.id yang Berisi Artikel Menarik",
      image: "/images/works/4.png",
      imageAlter: "/images/works/4_alter.png",
      solution:
        "Membuat backend manajemen blog menggunakan laravel dan membuat frontend end user menggunakan React dan ChakraUI (+dark mode)",
      narrative:
        "Kubu.id menawarkan platform web blog yang unik, berfokus pada ketenagakerjaan untuk para profesional yang sudah bekerja maupun calon pekerja. Di sini, pengguna dapat menemukan beragam artikel, panduan, dan tips terkait dunia kerja, serta konsultasi online dengan para profesional terkait. Selain itu, kubu.id juga menjadi tempat untuk membangun jaringan dan berbagi pengalaman antara sesama anggota komunitas. Dengan kombinasi pengetahuan, konsultasi, dan interaksi antaranggota, kubu.id menjadi sumber daya yang berharga bagi siapa pun yang ingin sukses dalam karir mereka.",
      ss: [
        "/images/works/3/ss/0.png",
        "/images/works/3/ss/1.png",
        "/images/works/3/ss/2.png",
        "/images/works/3/ss/3.png",
        "/images/works/3/ss/4.png",
        "/images/works/3/ss/5.png",
      ],
      ssScrollLength: 450,
      link: "https://blog.kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title: "Online Course dari Kubu.id Berbasis Web",
      image: "/images/works/5.png",
      imageAlter: "/images/works/5_alter.png",
      solution:
        "Membuat beberapa backend menggunakan laravel dan membuat frontend end user menggunakan React dan ChakraUI",
      narrative:
        "Web online course ini ditujukan untuk orang yang ingin mengikuti proses pembelajaran dengan cara daring. Kurikulum terstruktur dan akses video selanjutnya bisa diakses hanya dengan cara menyelesaikan video yang tersedia. Playback video tidak bisa dimajukan namun bisa disimpan max played nya.",
      ss: [
        "/images/works/2/ss/0.png",
        "/images/works/2/ss/1.png",
        "/images/works/2/ss/2.png",
        "/images/works/2/ss/3.png",
        "/images/works/2/ss/4.png",
        "/images/works/2/ss/5.png",
        "/images/works/2/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://course.kubu.id/",
    },

    // RSKI
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "RUMAH SAKIT KASIH IBU",
      title: "Aplikasi HR untuk Rumah Sakit Kasih Ibu",
      image: "/images/works/6.png",
      imageAlter: "/images/works/6_alter.png",
      solution:
        "Membuat webapp admin untuk mengelola master data dan presensi karyawan. Terdapat fitur pembuatan master data data karyawan, shift, keuangan,penggajian hingga pengaturan THR",
      narrative:
        "Data yang tersebar di berbagai departemen menyebabkan pengolahan informasi menjadi lambat dan rentan terhadap kesalahan. Untuk mengatasi masalah ini, RSKI memutuskan untuk membuat sebuah webapp admin yang mampu mengelola seluruh master data dan presensi karyawan secara terpusat dan otomatis.",
      ss: [
        "/images/works/6/ss/0.png",
        "/images/works/6/ss/1.png",
        "/images/works/6/ss/2.png",
        "/images/works/6/ss/3.png",
        "/images/works/6/ss/4.png",
        "/images/works/6/ss/5.png",
        "/images/works/6/ss/6.png",
        "/images/works/6/ss/7.png",
        "/images/works/6/ss/8.png",
        "/images/works/6/ss/9.png",
        "/images/works/6/ss/10.png",
        "/images/works/6/ss/11.png",
        "/images/works/6/ss/12.png",
        "/images/works/6/ss/13.png",
        "/images/works/6/ss/14.png",
        "/images/works/6/ss/15.png",
        "/images/works/6/ss/16.png",
        "/images/works/6/ss/17.png",
        "/images/works/6/ss/18.png",
      ],
      ssScrollLength: 450,
      demo: "https://rski-personalia.netlify.app/",
      helperText: "username: demo.account, password: 1234",
    },
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "RUMAH SAKIT KASIH IBU",
      title: "Aplikasi Karyawan untuk Rumah Sakit Kasih Ibu",
      image: "/images/works/7.png",
      imageAlter: "/images/works/7_alter.png",
      solution:
        "Membuat mobile app dan PWA untuk digunakan karyawan. Fitur utama pada aplikasi ini adalah presensi dengan foto dan geolokasi. Terdapat fitur lain dari permohonan cuti/izin, tukar shift, slip gaji. laporan hingga koperasi. Terintegrasi dengan alat fingerprint",
      narrative:
        "Data presensi menggunakan alat fingerprint sangat sulit untuk dikelola karena harus export dari alatnya dan kemudian di audit kembali yang memakan waktu cukup lama. Sistem informasi karyawan juga diperlukan untuk pengelolaan data karyawan agar semakin efisien.",
      ss: [
        "/images/works/7/ss/0.png",
        "/images/works/7/ss/1.png",
        "/images/works/7/ss/2.png",
        "/images/works/7/ss/3.png",
        "/images/works/7/ss/4.png",
        "/images/works/7/ss/5.png",
      ],
      ssScrollLength: 450,
      demo: "https://rski-karyawan.netlify.app/",
      helperText: "username: demo.account, password: 1234",
    },

    // Library Mahal
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "Distro Components & Library",
      title: "Reusable Custom Component & Custom Library (Starter Pack)",
      image: "/images/works/9.png",
      imageAlter: "/images/works/9.png",
      solution:
        "Agar proses pengembangan frontend di Exium Studio menjadi efisien, saya membuat library ini untuk saya gunakan pribadi (sementara), mungkin saya akan mempublikasikannya suatu hari nanti.",
      narrative:
        "Saya sebagai seorang Frontend di Exium Studio merasa membutuhkan custom komponen yang bisa digunakan kembali, karena jika tidak begitu, proses development jadi semakin lama dan tidak efisien.",
      ss: [
        "/images/works/9/ss/0.png",
        "/images/works/9/ss/1.png",
        "/images/works/9/ss/2.png",
        "/images/works/9/ss/3.png",
        "/images/works/9/ss/4.png",
        "/images/works/9/ss/5.png",
        "/images/works/9/ss/6.png",
        "/images/works/9/ss/7.png",
        "/images/works/9/ss/8.png",
        "/images/works/9/ss/9.png",
      ],
      ssScrollLength: 450,
      link: "https://library-mahal.netlify.app/",
    },

    // Geoportal
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "Geoportal",
      title: "Sistem Informasi Geografis",
      image: "/images/works/10.png",
      imageAlter: "/images/works/10_alter.png",
      solution:
        "Sistem GIS Pertanahan ini memungkinkan pengguna untuk melihat detail informasi tanah melalui fitur klik bidang, yang mencakup data sertifikat, NIK, NOP, jenis hak, luas tanah, serta tampilan peta satelit. Dilengkapi dengan fitur pengelolaan pengguna, import data SHP, dan dashboard untuk memonitor layer gap, overlap, serta LSD.",
      narrative:
        "Projek GIS Pertanahan yang saya kembangkan menyediakan solusi komprehensif dalam manajemen data pertanahan. Sistem ini dilengkapi dengan fitur interaktif di mana pengguna dapat mengklik pada bidang tanah di peta untuk menampilkan informasi lengkap, seperti nama pemilik, NIK, nomor sertifikat, NIB, NOP, jenis hak, luas tanah, alamat, dan pengelola lahan. Selain itu, sistem ini mendukung visualisasi data menggunakan tampilan satelit dan menyediakan dashboard canggih untuk memonitor gap, overlap, dan LSD pada layer-layer peta. Terdapat juga fitur pengelolaan pengguna serta kemampuan untuk mengimpor data berbasis SHP, memastikan fleksibilitas dan efisiensi dalam pengelolaan data pertanahan.",
      ss: [
        "/images/works/9/ss/0.png",
        "/images/works/9/ss/1.png",
        "/images/works/9/ss/2.png",
        "/images/works/9/ss/3.png",
        "/images/works/9/ss/4.png",
        "/images/works/9/ss/5.png",
        "/images/works/9/ss/6.png",
        "/images/works/9/ss/7.png",
        "/images/works/9/ss/8.png",
        "/images/works/9/ss/9.png",
      ],
      ssScrollLength: 450,
      // link: "https://library-mahal.netlify.app/",
    },
  ],

  en: [
    {
      category: 0,
      clientLogo: "/images/clients/gerindra.png",
      clientName: "Myself",
      title: "Just My First Old Personal Website",
      image: "/images/works/0.png",
      imageAlter: "/images/works/0.png",
      solution:
        "Creating a minimalist design using React and ChakraUI. The content data for this personal website is static and there are 2 language versions (Indonesian and English).",
      narrative:
        "As a fresh graduate, I wanted to have my own personal website. At that time, my knowledge of React was still basic but I had a good sense of design due to my 1-year experience as a graphic designer. So, I created my personal website with the skills I had at that time.",
      ss: [
        "/images/works/0/ss/0.png",
        "/images/works/0/ss/1.png",
        "/images/works/0/ss/2.png",
        "/images/works/0/ss/3.png",
        "/images/works/0/ss/4.png",
        "/images/works/0/ss/5.png",
        "/images/works/0/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://fatwalinoveraold.netlify.app/",
    },
    {
      category: 0,
      clientLogo: "/images/clients/gerindra.png",
      clientName: "Myself",
      title: "Just My Second Old Personal Website",
      image: "/images/works/-1.png",
      imageAlter: "/images/works/-1.png",
      solution:
        "Creating a minimalist design using React and ChakraUI. The content data for this personal website is static and there are 2 language versions (Indonesian and English).",
      narrative:
        "As a fresh graduate, I wanted to have my own personal website. At that time, my knowledge of React was still basic but I had a good sense of design due to my 1-year experience as a graphic designer. So, I created my personal website with the skills I had at that time.",
      ss: [
        "/images/works/-1/ss/0.png",
        "/images/works/-1/ss/1.png",
        "/images/works/-1/ss/2.png",
        "/images/works/-1/ss/3.png",
        "/images/works/-1/ss/4.png",
        "/images/works/-1/ss/5.png",
        "/images/works/-1/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://fatwalinoveraold2.netlify.app/",
    },

    {
      category: 0,
      clientLogo: "/images/clients/poltekkes.png",
      clientName: "POLTEKKES SEMARANG",
      title:
        "Platform for Laboratory Testing Transactions and Admin Dashboard to Manage the System",
      image: "/images/works/1.png",
      imageAlter: "/images/works/1_alter.png",
      solution:
        "As a frontend developer, I worked on the interface according to the design provided by the team and also implemented API requests.",
      narrative:
        "Poltekkes requested a system for lab testing. There are 2 users: customers and admins. Customers can create an account and request laboratory testing and monitor the process. Admins can manage the system such as testing methods, costs, dashboard, etc.",
      ss: [
        "/images/works/0/ss/0.png",
        "/images/works/0/ss/1.png",
        "/images/works/0/ss/2.png",
        "/images/works/0/ss/3.png",
        "/images/works/0/ss/4.png",
        "/images/works/0/ss/5.png",
        "/images/works/0/ss/6.png",
        "/images/works/0/ss/7.png",
        "/images/works/0/ss/8.png",
        "/images/works/0/ss/9.png",
        "/images/works/0/ss/10.png",
        "/images/works/0/ss/11.png",
        "/images/works/0/ss/12.png",
      ],
      ssScrollLength: 450,
      link: "https://lab.distrostudio.org/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title:
        "Admin Webapp to Manage Landing Page, Blog, Online Course Websites",
      image: "/images/works/2.png",
      imageAlter: "/images/works/2_alter.png",
      solution:
        "Creating the backend using Laravel. First, the role system was created (creating admin accounts). Then, CRUD logic for blogs and courses was implemented.",
      narrative:
        "A webapp admin was needed to manage the websites that would be created later. Actions like creating, updating, deleting, restoring must be available. This admin webapp also has specific admin roles like online course admin, blog admin, etc.",
      ss: [
        "/images/works/5/ss/0.png",
        "/images/works/5/ss/1.png",
        "/images/works/5/ss/2.png",
        "/images/works/5/ss/3.png",
        "/images/works/5/ss/4.png",
        "/images/works/5/ss/5.png",
        "/images/works/5/ss/6.png",
        "/images/works/5/ss/7.png",
        "/images/works/5/ss/8.png",
      ],
      ssScrollLength: 450,
      // link: "https://admin2.kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title:
        "All-in-One Landing Page for Kubu.id Websites (Kubu Mobile App, Blog, Online Course)",
      image: "/images/works/3.png",
      imageAlter: "/images/works/3_alter.png",
      solution:
        "Create a CMS (Content Management System) backend using Laravel and create a user frontend using React and ChakraUI (+dark mode)",
      narrative:
        "Kubu.id is an application with an online community base for those of you who are already working and for prospective workers. The aim is to become a center for knowledge and information related to employment, as a medium for online consultations with professionals, developing networks and sharing information.",
      ss: [
        "/images/works/4/ss/0.png",
        "/images/works/4/ss/1.png",
        "/images/works/4/ss/2.png",
        "/images/works/4/ss/3.png",
        "/images/works/4/ss/4.png",
        "/images/works/4/ss/5.png",
      ],
      ssScrollLength: 450,
      link: "https://kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title: "Kubu.id Blog Featuring Interesting Articles",
      image: "/images/works/4.png",
      imageAlter: "/images/works/4_alter.png",
      solution:
        "Create a blog management backend using Laravel and create a user frontend using React and ChakraUI (+dark mode)",
      narrative:
        "Kubu.id offers a unique web blog platform, focused on employment for working professionals and prospective workers. Here, users can find various articles, guides and tips related to the world of work, as well as online consultations with related professionals. Apart from that, Kubu.id is also a place to build networks and share experiences between fellow community members. With a combination of knowledge, consultation, and member-to-member interaction,buku.id becomes a valuable resource for anyone who wants to be successful in their career.",
      ss: [
        "/images/works/3/ss/0.png",
        "/images/works/3/ss/1.png",
        "/images/works/3/ss/2.png",
        "/images/works/3/ss/3.png",
        "/images/works/3/ss/4.png",
        "/images/works/3/ss/5.png",
      ],
      ssScrollLength: 450,
      link: "https://blog.kubu.id/",
    },
    {
      category: 0,
      clientLogo: "/logos/logo.png",
      clientName: "Bussiness Watch Indonesia",
      title: "Online Course dari Kubu.id Berbasis Web",
      image: "/images/works/5.png",
      imageAlter: "/images/works/5_alter.png",
      solution:
        "Developed several backends using Laravel and created the end user frontend using React and ChakraUI.",
      narrative:
        "This online course website is aimed at people who want to pursue learning through online means. It features a structured curriculum, and access to the next video can only be gained by completing the available video. Video playback cannot be fast-forwarded, but the maximum duration can be saved.",
      ss: [
        "/images/works/2/ss/0.png",
        "/images/works/2/ss/1.png",
        "/images/works/2/ss/2.png",
        "/images/works/2/ss/3.png",
        "/images/works/2/ss/4.png",
        "/images/works/2/ss/5.png",
        "/images/works/2/ss/6.png",
      ],
      ssScrollLength: 450,
      link: "https://course.kubu.id/",
    },

    // RSKI
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "RUMAH SAKIT KASIH IBU",
      title: "HR Application for Rumah Sakit Kasih Ibu",
      image: "/images/works/6.png",
      imageAlter: "/images/works/6_alter.png",
      solution:
        "Creating an admin webapp to manage employee master data and attendance. It includes features for creating employee master data, shifts, finances, payroll, and setting THR.",
      narrative:
        "Data scattered across various departments causes information processing to be slow and prone to errors. To address this issue, RSKI decided to create an admin webapp capable of centrally and automatically managing all employee master data and attendance.",
      ss: [
        "/images/works/6/ss/0.png",
        "/images/works/6/ss/1.png",
        "/images/works/6/ss/2.png",
        "/images/works/6/ss/3.png",
        "/images/works/6/ss/4.png",
        "/images/works/6/ss/5.png",
        "/images/works/6/ss/6.png",
        "/images/works/6/ss/7.png",
        "/images/works/6/ss/8.png",
        "/images/works/6/ss/9.png",
        "/images/works/6/ss/10.png",
        "/images/works/6/ss/11.png",
        "/images/works/6/ss/12.png",
        "/images/works/6/ss/13.png",
        "/images/works/6/ss/14.png",
        "/images/works/6/ss/15.png",
        "/images/works/6/ss/16.png",
        "/images/works/6/ss/17.png",
        "/images/works/6/ss/18.png",
      ],
      ssScrollLength: 450,
      demo: "https://rski-personalia.netlify.app/",
      helperText: "username: demo.account, password: 1234",
    },
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "RUMAH SAKIT KASIH IBU",
      title: "Employee Application for Rumah Sakit Kasih Ibu",
      image: "/images/works/7.png",
      imageAlter: "/images/works/7_alter.png",
      solution:
        "Creating a mobile app and PWA for employee use. The main feature of this application is attendance with photo and geolocation. Other features include leave/permit requests, shift exchange, salary slip, reports, and cooperatives. Integrated with fingerprint devices.",
      narrative:
        "Managing attendance data using fingerprint devices is very difficult because it has to be exported from the device and then audited again, which takes quite a long time. An employee information system is also needed for efficient employee data management.",
      ss: [
        "/images/works/7/ss/0.png",
        "/images/works/7/ss/1.png",
        "/images/works/7/ss/2.png",
        "/images/works/7/ss/3.png",
        "/images/works/7/ss/4.png",
        "/images/works/7/ss/5.png",
      ],
      ssScrollLength: 450,
      demo: "https://rski-karyawan.netlify.app/",
      helperText: "username: demo.account, password: 1234",
    },

    // Library Mahal
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "Distro Components & Library",
      title: "Reusable Custom Component & Custom Library (Starter Pack)",
      image: "/images/works/9.png",
      imageAlter: "/images/works/9.png",
      solution:
        "To make the frontend development process at Exium Studio more efficient, I created this library for my personal use (for now). I might publish it someday.",
      narrative:
        "As a Frontend Developer at Exium Studio, I felt the need for custom reusable components because without them, the development process would take longer and be less efficient.",
      ss: [
        "/images/works/9/ss/0.png",
        "/images/works/9/ss/1.png",
        "/images/works/9/ss/2.png",
        "/images/works/9/ss/3.png",
        "/images/works/9/ss/4.png",
        "/images/works/9/ss/5.png",
        "/images/works/9/ss/6.png",
        "/images/works/9/ss/7.png",
        "/images/works/9/ss/8.png",
        "/images/works/9/ss/9.png",
      ],
      ssScrollLength: 450,
      link: "https://library-mahal.netlify.app/",
    },

    // Geoportal
    {
      category: 0,
      clientLogo: "/images/clients/rski.png",
      clientName: "Geoportal",
      title: "Geographic Information System",
      image: "/images/works/10.png",
      imageAlter: "/images/works/10_alter.png",
      solution:
        "This Land GIS project allows users to view detailed land information through a click-on-field feature, displaying data such as certificate number, NIK, NOP, land rights type, land area, and satellite view. It also includes user management, SHP data import, and a dashboard for monitoring gap, overlap, and LSD layers.",
      narrative:
        "The Land GIS project I developed offers a comprehensive solution for land data management. It features an interactive system where users can click on a land plot to display detailed information, including the owner's name, NIK, certificate number, NIB, NOP, land rights type, land area, address, and land manager. The system supports satellite imagery visualization and provides an advanced dashboard to monitor gaps, overlaps, and LSD in map layers. Additionally, it includes user management functionality and the ability to import SHP-based data, ensuring flexibility and efficiency in managing land information.",
      ss: [
        "/images/works/10/ss/0.png",
        "/images/works/10/ss/1.png",
        "/images/works/10/ss/2.png",
        "/images/works/10/ss/3.png",
        "/images/works/10/ss/4.png",
        "/images/works/10/ss/5.png",
        "/images/works/10/ss/6.png",
        "/images/works/10/ss/7.png",
      ],
      ssScrollLength: 450,
      // link: "https://library-mahal.netlify.app/",
    },
  ],
};

export default worksData;
